create table if not exists public.professionals (
  id bigint generated by default as identity primary key,
  name text not null,
  initials text not null default 'PR',
  email text not null default '',
  license_number text not null default '',
  province text not null,
  city text not null default '',
  specialty text not null,
  availability text not null default 'Esta semana',
  address text not null default '',
  phone text not null default '',
  modality text not null default 'Presencial',
  work_days text not null default 'Lunes a viernes',
  schedule_notes text not null default '9 a 12 y 17 a 20',
  formation text not null default '',
  active boolean not null default true,
  progress integer not null default 60,
  coords jsonb not null default '{"top":"49%","left":"66%"}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.professionals add column if not exists email text not null default '';
alter table public.professionals add column if not exists license_number text not null default '';
alter table public.professionals add column if not exists city text not null default '';
alter table public.professionals add column if not exists modality text not null default 'Presencial';
alter table public.professionals add column if not exists work_days text not null default 'Lunes a viernes';
alter table public.professionals add column if not exists schedule_notes text not null default '9 a 12 y 17 a 20';

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  professional_id bigint not null references public.professionals(id) on delete cascade,
  professional_name text not null,
  date_label text not null,
  date_iso date not null,
  time text not null,
  child_name text not null,
  parent_name text not null,
  parent_email text not null,
  whatsapp text not null,
  reason text,
  status text not null default 'Confirmado',
  created_at timestamptz not null default now(),
  unique (professional_id, date_iso, time)
);

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  role text not null check (role in ('family', 'professional', 'admin')),
  name text not null,
  email text not null,
  whatsapp text,
  child_name text,
  child_age text,
  consultation_reason text,
  specialty text,
  license_number text,
  province text,
  internal_code text,
  password_hash text not null default '',
  status text not null default 'Pendiente',
  created_at timestamptz not null default now(),
  unique (role, email)
);

alter table public.professionals enable row level security;
alter table public.appointments enable row level security;
alter table public.app_users enable row level security;

alter table public.app_users add column if not exists password_hash text not null default '';

drop policy if exists "Lectura publica de profesionales" on public.professionals;
create policy "Lectura publica de profesionales"
on public.professionals for select
to anon, authenticated
using (true);

drop policy if exists "ABM demo de profesionales" on public.professionals;
create policy "ABM demo de profesionales"
on public.professionals for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Lectura demo de turnos" on public.appointments;
create policy "Lectura demo de turnos"
on public.appointments for select
to anon, authenticated
using (true);

drop policy if exists "Reserva demo de turnos" on public.appointments;
create policy "Reserva demo de turnos"
on public.appointments for insert
to anon, authenticated
with check (true);

drop policy if exists "Actualizacion demo de turnos" on public.appointments;
create policy "Actualizacion demo de turnos"
on public.appointments for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Lectura demo de usuarios" on public.app_users;
create policy "Lectura demo de usuarios"
on public.app_users for select
to anon, authenticated
using (true);

drop policy if exists "Registro demo de usuarios" on public.app_users;
create policy "Registro demo de usuarios"
on public.app_users for insert
to anon, authenticated
with check (true);

drop policy if exists "ABM demo de usuarios" on public.app_users;
create policy "ABM demo de usuarios"
on public.app_users for update
to anon, authenticated
using (true)
with check (true);

insert into public.professionals
  (id, name, initials, email, license_number, province, city, specialty, availability, address, phone, modality, work_days, schedule_notes, formation, active, progress, coords)
values
  (1, 'Lic. Mariana Torres', 'MT', 'mariana@psicopuente.com', 'MP 1001', 'Buenos Aires', 'CABA', 'Dificultades de aprendizaje', 'Esta semana', 'Av. Rivadavia 1845, CABA', '5491134567890', 'Presencial', 'Lunes a viernes', '9 a 12 y 17 a 20', 'Licenciada en Psicopedagogia. Orientacion en alfabetizacion inicial y apoyo escolar.', true, 76, '{"top":"49%","left":"66%"}'),
  (2, 'Lic. Pablo Sosa', 'PS', 'pablo@psicopuente.com', 'MP 1002', 'Cordoba', 'Cordoba', 'Orientacion vocacional', 'Manana', 'Bv. San Juan 720, Cordoba', '5493514567890', 'Presencial y virtual', 'Lunes a viernes', '9 a 12 y 17 a 20', 'Psicopedagogo especializado en adolescentes, proyectos escolares y orientacion vocacional.', true, 64, '{"top":"43%","left":"48%"}'),
  (3, 'Lic. Sofia Pereyra', 'SP', 'sofia@psicopuente.com', 'MP 1003', 'Mendoza', 'Mendoza', 'Atencion y funciones ejecutivas', 'Proxima semana', 'San Martin 1120, Mendoza', '5492614567890', 'Presencial', 'Lunes a viernes', '9 a 12 y 17 a 20', 'Especialista en procesos atencionales, planificacion y estrategias de estudio.', true, 82, '{"top":"52%","left":"34%"}'),
  (4, 'Lic. Valeria Gomez', 'VG', 'valeria@psicopuente.com', 'MP 1004', 'Santa Fe', 'Rosario', 'Primera infancia', 'Esta semana', 'Pellegrini 890, Rosario', '5493414567890', 'Presencial', 'Lunes a viernes', '9 a 12 y 17 a 20', 'Acompanamiento temprano, desarrollo infantil y trabajo con familias.', true, 71, '{"top":"39%","left":"58%"}')
on conflict (id) do nothing;

insert into public.appointments
  (id, professional_id, professional_name, date_label, date_iso, time, child_name, parent_name, parent_email, whatsapp, reason, status)
values
  (1, 1, 'Lic. Mariana Torres', 'Miercoles 10/06/2026 10:00', '2026-06-10', '10:00', 'Mateo', 'Carolina Ruiz', 'carolina@email.com', '+5493884322437', 'Dificultades para sostener la atencion y organizar tareas escolares.', 'Confirmado')
on conflict (professional_id, date_iso, time) do nothing;

insert into public.app_users
  (role, name, email, whatsapp, specialty, license_number, province, password_hash, status)
values
  ('admin', 'Administrador Psico-Puente', 'admin@psicopuente.com', '', '', '', '', 'admin123', 'Activo'),
  ('professional', 'Lic. Mariana Torres', 'mariana@psicopuente.com', '5491134567890', 'Dificultades de aprendizaje', 'MP 1001', 'Buenos Aires', 'medico123', 'Activo'),
  ('professional', 'Lic. Pablo Sosa', 'pablo@psicopuente.com', '5493514567890', 'Orientacion vocacional', 'MP 1002', 'Cordoba', 'medico123', 'Activo')
on conflict (role, email) do nothing;
